module "ui" {
  source                 = "../../modules/okta-spa"
  stack_name             = "${var.stack[terraform.workspace]}"
  dns_prefix             = "${var.dns_prefix[terraform.workspace]}"
  environment            = "${var.environment}"
  stack                  = "${var.stack}"
  keypair                = "${var.keypair[terraform.workspace]}"
  aws_region             = "${var.aws_region[terraform.workspace]}"
  vpc_id                 = "${var.vpc_id[terraform.workspace]}"
  subnet_ids             = "${var.subnet_ids[terraform.workspace]}"
  dmz_subnet_ids         = "${var.dmz_subnet_ids[terraform.workspace]}"
  aws_route53_zone       = "${var.aws_route53_zone[terraform.workspace]}"
  ami                    = "${var.ami[terraform.workspace]}"
  datadog_api_key        = "${local.datadog_api_key}"
  splunk_token           = "${local.splunk_token}"
  gitlab_token           = "${local.gitlab_token}"
  fluentbit_docker_image = "${var.fluentbit_docker_image[terraform.workspace]}"
  ddagent_docker_image   = "${var.ddagent_docker_image[terraform.workspace]}"
  aws_profile            = "${var.aws_profile[terraform.workspace]}"
  number_of_nodes        = "${var.number_of_nodes[terraform.workspace]}"
  instance_type          = "${var.instance_type[terraform.workspace]}"
  okta_spa_docker_image    = "${var.okta_spa_docker_image_base[terraform.workspace]}:${var.release}${var.environment == "prod" ? "" : "-${var.environment}"}"
  release                = "${var.release}"
  lb_ssl_certificate_id  = "${var.lb_ssl_certificate_id[terraform.workspace]}"
  application_port       = "${var.application_port[terraform.workspace]}"
}
